[package]
name = "dir-formatter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
prettytable-rs = "^0.10"
humanize-rs = "0.1"